site_name: James Labs
site_description: Experiments, projects, and architecture notes.
site_url: https://ready2k.github.io/portfolio-examples/
repo_url: https://github.com/Ready2k/portfolio-examples
repo_name: Ready2k/portfolio-examples
edit_uri: edit/main/docs/

strict: true   # Fail build on broken links — helps keep everything clean

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - toc.integrate
    - search.suggest
    - content.action.edit      # “Edit this page” button
    - content.action.view      # “View source” button
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  - glightbox

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Projects:
      - projects/_index.md
      - projects/project-1.md
      - projects/project-2.md
      - projects/project-3.md
      - projects/project-4.md
      - projects/project-5.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js

extra_css:
  - css/extra.css